name = "metacogna-ai-worker"
main = "worker.js"
compatibility_date = "2024-06-08"

[env]
route = "kv.metacogna.ai/*"


[vars]
PORTAL_UPDATES_ID = "b8047f15afdb4aa9ace07c4cc5080c29"
COGNITO_REGION = "ap-southeast-2"
COGNITO_USER_POOL_ID = "ap-southeast-2_fgz2vg9Lq"
COGNITO_CLIENT_ID = "Ov23libUijHS9BJoA7ye"

[[kv_namespaces]]
binding = "PORTAL_UPDATES"
id = "b8047f15afdb4aa9ace07c4cc5080c29"
# to deploy to prod, set id for production KV namespace

[[d1_databases]]
binding = "PORTAL_DB"
database_name = "metacogna-portal"
database_id = "507bfe41-6173-4ab7-915a-022133b76117"

[ai]
binding = "AI"
